stages:
  load:
    cmd: 
     - ./src/ingest/load.py data/raw/ CVE-2012-2122 train data/interim/CVE-2012-2122/
     - ./src/ingest/load.py data/raw/ CVE-2012-2122 test data/interim/CVE-2012-2122/
     - ./src/ingest/load.py data/raw/ CVE-2012-2122 validation data/interim/CVE-2012-2122/
    deps: 
     -  data/raw/
    outs: 
     - train.csv
     - y_train.csv
     - test.csv
     - y_test.csv
     - validation.csv
     - y_validation.csv
  
  #train:
  #  cmd:
  #   - ./src/model/train.py data/interim/ IsolationForest CVE-2012-2122 data/model/CVE-2012-2122/IsoForest.pkl
  #  deps:
  #  outs:

  # test: 
  #   cmd:

  
  # evaluate:
  #   cmd:
  #   deps:
  #   plots:


    