stages:
  load:
    cmd: 
     - ./src/ingest/load.py data/raw/ CVE-2012-2122 train data/interim/CVE-2012-2122/
     - ./src/ingest/load.py data/raw/ CVE-2012-2122 test data/interim/CVE-2012-2122/
     - ./src/ingest/load.py data/raw/ CVE-2012-2122 validation data/interim/CVE-2012-2122/
    deps: 
     -  data/raw/
    outs: 
     - data/interim/CVE-2012-2122/train.csv
     - data/interim/CVE-2012-2122/y_train.csv
     - data/interim/CVE-2012-2122/test.csv
     - data/interim/CVE-2012-2122/y_test.csv
     - data/interim/CVE-2012-2122/validation.csv
  
  training:
    cmd:
     - ./src/model/train.py data/interim/ data/model/CVE-2012-2122 CVE-2012-2122 IForest 
     - ./src/model/train.py data/interim/ data/model/CVE-2012-2122 CVE-2012-2122 LOF
     - ./src/model/train.py data/interim/ data/model/CVE-2012-2122 CVE-2012-2122 VAE
     - ./src/model/train.py data/interim/ data/model/CVE-2012-2122 CVE-2012-2122 KNN
     - ./src/model/train.py data/interim/ data/model/CVE-2012-2122 CVE-2012-2122 KMEANS
     - ./src/model/train.py data/interim/ data/model/CVE-2012-2122 CVE-2012-2122 DBSCAN
    deps:
     - data/interim
    outs:
     - data/model/CVE-2012-2122/IForest.pkl
     - data/model/CVE-2012-2122/LOF.pkl
     - data/model/CVE-2012-2122/VAE.pkl
     - data/model/CVE-2012-2122/KMEANS.pkl
     - data/model/CVE-2012-2122/DBSCAN.pkl
     - data/model/CVE-2012-2122/KNN.pkl
  
  predict:
    cmd:
     - ./src/model/predict.py data/interim/ data/predictions/ CVE-2012-2122 IForest
     - ./src/model/predict.py data/interim/ data/predictions/ CVE-2012-2122 LOF
     - ./src/model/predict.py data/interim/ data/predictions/ CVE-2012-2122 VAE
     - ./src/model/predict.py data/interim/ data/predictions/ CVE-2012-2122 KMEANS
     - ./src/model/predict.py data/interim/ data/predictions/ CVE-2012-2122 DBSCAN
     - ./src/model/predict.py data/interim/ data/predictions/ CVE-2012-2122 KNN
    deps:
     - data/interim/
    outs:
     - data/predictions/CVE-2012-2122/predictions_IForest.csv
     - data/predictions/CVE-2012-2122/predictions_LOF
     - data/predictions/CVE-2012-2122/predictions_VAE.csv
     - data/predictions/CVE-2012-2122/predictions_KMEANS.csv
     - data/predictions/CVE-2012-2122/predictions_DBSCAN.csv
     - data/predictions/CVE-2012-2122/predictions_KNN.csv

  evaluate:
    cmd: 
     - ./src/model/evaluate.py data/interim data/predictions data/predictions/ CVE-2012-2122 IForest
     - ./src/model/evaluate.py data/interim data/predictions data/predictions/ CVE-2012-2122 LOF
     - ./src/model/evaluate.py data/interim data/predictions data/predictions/ CVE-2012-2122 VAE
     - ./src/model/evaluate.py data/interim data/predictions data/predictions/ CVE-2012-2122 KMEANS
     - ./src/model/evaluate.py data/interim data/predictions data/predictions/ CVE-2012-2122 DBSCAN
     - ./src/model/evaluate.py data/interim data/predictions data/predictions/ CVE-2012-2122 KNN

    outs:
     - data/predictions/CVE-2012-2122/metrics_IForest.json
     - data/predictions/CVE-2012-2122/results_IForest.json
   
  
  plot:
    cmd: 
     - ./src/visualize/table.py data/predictions/CVE-2012-2122/metrics_IForest.json > data/predictions/CVE-2012-2122/table_IForest.md
     - 
    outs:
     - src/results/plots/table.md

 





    