stages:
  load:
    cmd: 
     - ./src/ingest/load.py data/raw/ CVE-2012-2122 train data/interim/CVE-2012-2122/
     - ./src/ingest/load.py data/raw/ CVE-2012-2122 test data/interim/CVE-2012-2122/
     - ./src/ingest/load.py data/raw/ CVE-2012-2122 validation data/interim/CVE-2012-2122/
    deps: 
     -  data/raw/
    outs: 
     - data/interim/CVE-2012-2122/train.csv
     - data/interim/CVE-2012-2122/y_train.csv
     - data/interim/CVE-2012-2122/test.csv
     - data/interim/CVE-2012-2122/y_test.csv
     - data/interim/CVE-2012-2122/validation.csv
  
  training:
    cmd:
     - ./src/model/train.py data/interim/ CVE-2012-2122 data/model/CVE-2012-2122 IForest
    deps:
     - data/interim
    outs:
     - data/model/CVE-2012-2122/IForest.pkl
  
  predict:
    cmd:
     - ./src/model/predict.py data/interim/ CVE-2012-2122 IForest data/predictions/
    deps:
     - data/interim/
    outs:
     - data/predictions/CVE-2012-2122/predictions.csv
  

  evaluate:
    cmd: 
    - ./src/model/evaluate.py data/interim data/predictions CVE-2012-2122 src/results/metrics
    outs:
    - src/results/metrics/results.csv
    plots:
      - src/results/metrics/results.csv:
        x: actual
        y: predicted
        template: confusion
        x_label: Actual Class
        y_label: Predicted class
      






    