IForest:
  n_estimators: [30, 50, 100, 150]
  max_samples: auto
  contamination: [0.01, 0.05, 0.1, 0.25, 0.5]
  max_features: [0.2, 0.5, 1.0]
  bootstrap: [True, False]
  n_jobs: -1 
  random_state: 42
  verbose: 0

LOF:
  n_neighbors: [10, 30, 50]
  algorithm: auto
  leaf_size: [10, 30, 50]
  p: [1, 2, 5]
  contamination: [0.01, 0.05, 0.1, 0.25, 0.5]
  novelty: True
  n_jobs: -1

VAE:
  encoder_neurons: [1, 32]
  decoder_neurons: [32, 1]
  hidden_activation: relu
  output_activation: sigmoid
  optimizer: adam
  epochs: [10, 50, 100]
  batch_size: [16, 32, 64, 128]
  dropout_rate: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5]
  l2_regularizer: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5]
  validation_size: [0.1, 0.2, 0.5] 
  preprocessing: True 
  verbose: 0 
  random_state: None 
  contamination: [0.01, 0.05, 0.1, 0.25, 0.5]
  gamma: 1.0 
  capacity: 0.0

KNN:
 contamination: [0.01, 0.05, 0.1, 0.25, 0.5]
 n_neighbours: [10, 30, 50]
 method: [largest, mean, median]
 radius: [0.5, 1.0]
 algorithm: [auto, ball_tree, kd_tree, brute]
 leaf_size: [10, 30, 50]
 metric: [l1, l2]
 p: [1, 2, 5]
 n_jobs: -1
