IsolationForest:
  n_estimators: 100
  max_samples: 'auto'
  contamination: 'auto'
  max_features: 1.0
  bootstrap: False
  n_jobs: -1 
  random_state: 42
  verbose: 0

LocalOutlierFactor:
  n_neighbors: 20
  algorithm: 'auto'
  leaf_size: 30
  p: 2
  contamination: 0.1532595823344213
  novelty: True
  n_jobs: -1

