KNN:
  n_neighbours: 2

IsolationForest:
  n_estimators: 100
  max_samples: 'auto'
  contamination: 0.1532595823344213
  max_features: 1.0
  bootstrap: False
  n_jobs: -1 
  random_state: 42
  verbose: 0

LocalOutlierFactor:
  n_neighbours: 20
  algorithm: 'auto'
  leaf_size: 30
  p: 2
  contamination: 0.1532595823344213
  novelty: True
  n_jobs: -1

DBSCAN:
  eps: 0.5 
  min_samples: 5
  metric: 'euclidean'
  algorithm: 'auto'
  leaf_size: 30

SVM:
  kernel: 'sigmoid'