IForest:
  n_estimators: 100
  max_samples: 'auto'
  contamination: 0.1
  max_features: 1.0
  bootstrap: False
  n_jobs: -1 
  random_state: 42
  verbose: 0

LOF:
  n_neighbors: 20
  algorithm: 'auto'
  leaf_size: 30
  p: 2
  contamination: 0.1
  novelty: True
  n_jobs: -1

VAE:
  encoder_neurons: [1, 32]
  decoder_neurons: [32, 1]
  hidden_activation: relu
  output_activation: sigmoid
  optimizer: adam
  epochs: 100
  batch_size: 32
  dropout_rate: 0.2
  l2_regularizer: 0.1
  validation_size: 0.1 
  preprocessing: True 
  verbose: 0 
  random_state: None 
  contamination: 0.1 
  gamma: 1.0 
  capacity: 0.0

