IsolationForest:
  n_estimators: 100
  max_samples: 'auto'
  contamination: 0.1532595823344213
  max_features: 1.0
  bootstrap: False
  n_jobs: -1 
  random_state: 42
  verbose: 0

LocalOutlierFactor:
  n_neighbours:
  algorithm: 
  leaf_size:
  metric:
  p:
  contanimation:
  novelty:
  n_josb: